### PR TITLE
Organize repo - Major codebase change

### PR DESCRIPTION
**Pull request by timiimit**
This PR organizes repository. I don't expect anyone to look through the code.

The following was performed:
- put related classes into same namespace and folder
- separate the backend code into multiple project modules
- at a couple of places Newtonsoft library was replaced with System.Text.Json which follows #33
- a couple more minor changes were made

c# code was split up because I was working on #26. I wrote a c# XMPP server which needs some knowledge of classes used in main master server and both will need to communicate directly (most likely over a simple tcp connection).

Before merging i still need to test whether everything is operational. When that's done, I will duplicate current master branch to another branch. This way it will be easier to see what this PR messed up if later down the line we discover something isn't working.

### CODE REVIEW

**Comment by timiimit** [comment]
Looks like everything is working. I will merge this after #162 is merged.

**Comment by Saibamen** [comment]
I'm will not be available this weekend. Can you check if our paths (both trigger and ignore) in GH Actions need to be changed? Thanks

**Comment by timiimit** [comment]
As agreed with @belmirp I merged this before #162

**Comment by timiimit** [comment]
@Saibamen I think it looks fine as is, but I'm no expert.

**Pull request merged**
