### PR TITLE
Verify that `EpicID` is a hexadecimal string

### PR DESCRIPTION
**Pull request by Saibamen**

### CODE REVIEW

**Comment by timiimit** [comment]
i already did this earlier today

**Comment by Saibamen** [comment]
@timiimit: But you created custom code. Why not to use standard C# methods?

**Comment by timiimit** [comment]
Are you sure your code would work? That method is used to parse an int, which is 4 bytes long. the id string parameter can represent a 16 byte number.

**Comment by Saibamen** [comment]
> Are you sure your code would work? That method is used to parse an int, which is 4 bytes long. the id string parameter can represent a 16 byte number.

I wrote xUnit tests and your code is better: https://github.com/timiimit/UT4MasterServer/pull/32

**Pull request closed without merging**
