### PR TITLE
Optimize images

### PR DESCRIPTION
**Pull request by Saibamen**
### Flags
image

### Avatars
image

### CODE REVIEW

**Comment by timiimit** [comment]
Uruguay and Zimbabwe increased in size.
I'm not sure if we want to compress these images. Images already are small and if we compress them we lose originals.
Also i maybe see some slight differences between some images. Maybe only compressing non-complex images would be better.
idk, i have to think about this.

**Comment by Saibamen** [comment]
> Uruguay and Zimbabwe increased in size.
In screenshot, they are this same

**Comment by timiimit** [comment]
github says they are larger.

image

**Comment by Saibamen** [comment]
Fixed

**Comment by timiimit** [comment]
OK i have decided. Please remove changes of avatars, i would like to just optimize Flags.

**Comment by Saibamen** [comment]
Done

**Review by timiimit — APPROVED** [review]

**Pull request merged**
